services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
    volumes:
      - db_volume:/data
    ports:
      - "5000:5000"
    environment:
      - DATABASE_PATH=/data/database.db
    depends_on:
      - database
  
  database:
    build: ./database
    volumes:
      - db_volume:/data

volumes:
  db_volume:
